prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/application_configuration.sql
@@application/shared_components/navigation/lists/activity_reports.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/rejestracja.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/icons_screw_svg.sql
@@application/shared_components/files/icons_nut_svg.sql
@@application/shared_components/files/icons_questionmark_svg.sql
@@application/shared_components/files/icons_all_css.sql
@@application/shared_components/files/icons_all_min_css.sql
@@application/shared_components/files/icons_sruby_jpg.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/reader_rights.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/security/authorizations/prawa_kierownika.sql
@@application/shared_components/security/authorizations/prawa_właściciela.sql
@@application/shared_components/security/authorizations/prawa_managera.sql
@@application/shared_components/security/authorizations/prawa_klienta.sql
@@application/shared_components/security/authorizations/prawa_pracownika.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/contributor.sql
@@application/shared_components/security/app_access_control/reader.sql
@@application/shared_components/security/app_access_control/wlasciciel_r.sql
@@application/shared_components/security/app_access_control/manager_r.sql
@@application/shared_components/security/app_access_control/kierownik_r.sql
@@application/shared_components/security/app_access_control/pracownik_r.sql
@@application/shared_components/security/app_access_control/klient_r.sql
@@application/shared_components/security/app_access_control/gosc_r.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/view_as_report_chart.sql
@@application/shared_components/user_interface/lovs/wydanie_certyfikatu_dodatku_symbol_dodatku.sql
@@application/shared_components/user_interface/lovs/wydanie_certyfikatu_sruby_id_sruby.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/drawer_002.sql
@@application/shared_components/user_interface/templates/page/master_detail_002.sql
@@application/shared_components/user_interface/templates/page/modal_dialog_002.sql
@@application/shared_components/user_interface/templates/page/login_002.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog_002.sql
@@application/shared_components/user_interface/templates/page/left_side_column_002.sql
@@application/shared_components/user_interface/templates/page/right_side_column_002.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns_002.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation_002.sql
@@application/shared_components/user_interface/templates/page/standard_002.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/icon_002.sql
@@application/shared_components/user_interface/templates/button/text_002.sql
@@application/shared_components/user_interface/templates/button/text_with_icon_002.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/search_results_container.sql
@@application/shared_components/user_interface/templates/region/item_container.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/inline_popup_002.sql
@@application/shared_components/user_interface/templates/region/search_results_container_002.sql
@@application/shared_components/user_interface/templates/region/item_container_002.sql
@@application/shared_components/user_interface/templates/region/inline_drawer_002.sql
@@application/shared_components/user_interface/templates/region/image_002.sql
@@application/shared_components/user_interface/templates/region/alert_002.sql
@@application/shared_components/user_interface/templates/region/cards_container_002.sql
@@application/shared_components/user_interface/templates/region/interactive_report_002.sql
@@application/shared_components/user_interface/templates/region/wizard_container_002.sql
@@application/shared_components/user_interface/templates/region/buttons_container_002.sql
@@application/shared_components/user_interface/templates/region/content_block_002.sql
@@application/shared_components/user_interface/templates/region/title_bar_002.sql
@@application/shared_components/user_interface/templates/region/collapsible_002.sql
@@application/shared_components/user_interface/templates/region/inline_dialog_002.sql
@@application/shared_components/user_interface/templates/region/hero_002.sql
@@application/shared_components/user_interface/templates/region/login_002.sql
@@application/shared_components/user_interface/templates/region/carousel_container_002.sql
@@application/shared_components/user_interface/templates/region/tabs_container_002.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid_002.sql
@@application/shared_components/user_interface/templates/region/standard_002.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_002.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs_002.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu_002.sql
@@application/shared_components/user_interface/templates/list/wizard_progress_002.sql
@@application/shared_components/user_interface/templates/list/menu_bar_002.sql
@@application/shared_components/user_interface/templates/list/badge_list_002.sql
@@application/shared_components/user_interface/templates/list/media_list_002.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu_002.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu_002.sql
@@application/shared_components/user_interface/templates/list/navigation_bar_002.sql
@@application/shared_components/user_interface/templates/list/cards_002.sql
@@application/shared_components/user_interface/templates/list/tabs_002.sql
@@application/shared_components/user_interface/templates/list/menu_popup_002.sql
@@application/shared_components/user_interface/templates/list/links_list_002.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/timeline_002.sql
@@application/shared_components/user_interface/templates/report/content_row_002.sql
@@application/shared_components/user_interface/templates/report/media_list_002.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row_002.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column_002.sql
@@application/shared_components/user_interface/templates/report/badge_list_002.sql
@@application/shared_components/user_interface/templates/report/contextual_info_002.sql
@@application/shared_components/user_interface/templates/report/standard_002.sql
@@application/shared_components/user_interface/templates/report/comments_002.sql
@@application/shared_components/user_interface/templates/report/alerts_002.sql
@@application/shared_components/user_interface/templates/report/cards_002.sql
@@application/shared_components/user_interface/templates/report/search_results_002.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/hidden_002.sql
@@application/shared_components/user_interface/templates/label/optional_002.sql
@@application/shared_components/user_interface/templates/label/optional_above_002.sql
@@application/shared_components/user_interface/templates/label/optional_floating_002.sql
@@application/shared_components/user_interface/templates/label/required_002.sql
@@application/shared_components/user_interface/templates/label/required_above_002.sql
@@application/shared_components/user_interface/templates/label/required_floating_002.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb_002.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/templates/calendar/calendar_002.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/plugins/template_component/theme_42_avatar.sql
@@application/shared_components/plugins/template_component/theme_42_badge.sql
@@application/shared_components/plugins/template_component/theme_42_button.sql
@@application/shared_components/plugins/template_component/theme_42_comments.sql
@@application/shared_components/plugins/template_component/theme_42_content_row.sql
@@application/shared_components/plugins/template_component/theme_42_media_list.sql
@@application/shared_components/plugins/template_component/theme_42_timeline.sql
@@application/shared_components/plugins/template_component/theme_100_avatar.sql
@@application/shared_components/plugins/template_component/theme_100_badge.sql
@@application/shared_components/plugins/template_component/theme_100_button.sql
@@application/shared_components/plugins/template_component/theme_100_comments.sql
@@application/shared_components/plugins/template_component/theme_100_content_row.sql
@@application/shared_components/plugins/template_component/theme_100_media_list.sql
@@application/shared_components/plugins/template_component/theme_100_timeline.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00020.sql
@@application/pages/page_00030.sql
@@application/pages/page_00040.sql
@@application/pages/page_00060.sql
@@application/pages/page_00070.sql
@@application/pages/page_00071.sql
@@application/pages/page_00072.sql
@@application/pages/page_00100.sql
@@application/pages/page_00110.sql
@@application/pages/page_00115.sql
@@application/pages/page_00201.sql
@@application/pages/page_00202.sql
@@application/pages/page_00205.sql
@@application/pages/page_00210.sql
@@application/pages/page_00220.sql
@@application/pages/page_00221.sql
@@application/pages/page_00230.sql
@@application/pages/page_00235.sql
@@application/pages/page_00301.sql
@@application/pages/page_00302.sql
@@application/pages/page_00305.sql
@@application/pages/page_00310.sql
@@application/pages/page_00320.sql
@@application/pages/page_00321.sql
@@application/pages/page_00330.sql
@@application/pages/page_00335.sql
@@application/pages/page_00401.sql
@@application/pages/page_00500.sql
@@application/pages/page_00504.sql
@@application/pages/page_00505.sql
@@application/pages/page_00601.sql
@@application/pages/page_00701.sql
@@application/pages/page_00711.sql
@@application/pages/page_00721.sql
@@application/pages/page_00800.sql
@@application/pages/page_00801.sql
@@application/pages/page_00802.sql
@@application/pages/page_00803.sql
@@application/pages/page_00804.sql
@@application/pages/page_00805.sql
@@application/pages/page_00806.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10020.sql
@@application/pages/page_10021.sql
@@application/pages/page_10022.sql
@@application/pages/page_10023.sql
@@application/pages/page_10024.sql
@@application/pages/page_10025.sql
@@application/pages/page_10026.sql
@@application/pages/page_10030.sql
@@application/pages/page_10031.sql
@@application/pages/page_10032.sql
@@application/pages/page_10033.sql
@@application/pages/page_10034.sql
@@application/pages/page_99991.sql
@@application/pages/page_99992.sql
@@application/pages/page_99993.sql
@@application/pages/page_99994.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
