prompt --application/pages/page_00210
begin
--   Manifest
--     PAGE: 00210
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2023.04.28'
,p_release=>'23.1.5'
,p_default_workspace_id=>8358547342345319
,p_default_application_id=>120
,p_default_id_offset=>0
,p_default_owner=>'WKSP_WS151783'
);
wwv_flow_imp_page.create_page(
 p_id=>210
,p_name=>'dod_z_sr'
,p_alias=>'DOD-Z-SR'
,p_page_mode=>'MODAL'
,p_step_title=>unistr('\015Aruby pasuj\0105ce do dodatk\00F3w')
,p_autocomplete_on_off=>'OFF'
,p_group_id=>wwv_flow_imp.id(64799221816860008)
,p_step_template=>wwv_flow_imp.id(127720327755451391)
,p_page_template_options=>'#DEFAULT#:js-dialog-class-t-Drawer--pullOutEnd'
,p_protection_level=>'C'
,p_page_component_map=>'18'
,p_last_updated_by=>'KACPER.KURAS@STUDENT.PUT.POZNAN.PL'
,p_last_upd_yyyymmddhh24miss=>'20240110112145'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(115111826722508349)
,p_plug_name=>'dod_z_sr'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(127779121151451441)
,p_plug_display_sequence=>30
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT ',
unistr('NAZWA_SRUBY || '' Kl. '' || KLASA_WYTRZYMALOSCI || '' Materia\0142: '' ||'),
unistr(' MATERIAL || '' '' || KOLOR || '' \0141eb: '' || RODZAJ_LBA || '' Gniazdo: '' || GNIAZDO  as NAZWA, '),
' ID_SRUBY',
' FROM SRUBA NATURAL JOIN SRUBA_DODATEK WHERE id_dodatku=:P210_ID_DODATKU'))
,p_plug_source_type=>'NATIVE_IR'
,p_ajax_items_to_submit=>'P210_ID_DODATKU'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header=>'sr_z_dod'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(115124772564565253)
,p_max_row_count=>'1000000'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_show_finder_drop_down=>'N'
,p_report_list_mode=>'NONE'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'KACPER.KURAS@STUDENT.PUT.POZNAN.PL'
,p_internal_uid=>115124772564565253
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(183682839515036040)
,p_db_column_name=>'NAZWA'
,p_display_order=>10
,p_column_identifier=>'G'
,p_column_label=>unistr('\015Aruba')
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(64742361718268145)
,p_db_column_name=>'ID_SRUBY'
,p_display_order=>20
,p_column_identifier=>'D'
,p_column_label=>'Informacje'
,p_column_link=>'f?p=&APP_ID.:305:&SESSION.::&DEBUG.:305:P305_ID_SRUBY:#ID_SRUBY#'
,p_column_linktext=>'<span class="fa fa-wrench"></span>'
,p_allow_sorting=>'N'
,p_allow_filtering=>'N'
,p_allow_highlighting=>'N'
,p_allow_ctrl_breaks=>'N'
,p_allow_aggregations=>'N'
,p_allow_computations=>'N'
,p_allow_charting=>'N'
,p_allow_group_by=>'N'
,p_allow_pivot=>'N'
,p_allow_hide=>'N'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(119381483092737571)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'545594'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'ID_SRUBY:NAZWA:'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(64823883337894439)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(115111826722508349)
,p_button_name=>'Tab_dod'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(127896059539451539)
,p_button_image_alt=>unistr('Zobacz \015Bruby na pe\0142nej stronie')
,p_button_redirect_url=>'f?p=&APP_ID.:320:&SESSION.::&DEBUG.:::'
,p_grid_new_row=>'Y'
,p_security_scheme=>wwv_flow_imp.id(21995650961848200)
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(115125453161565242)
,p_name=>'P210_ID_DODATKU'
,p_item_sequence=>20
,p_display_as=>'NATIVE_HIDDEN'
,p_attribute_01=>'Y'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(64824745001894440)
,p_process_sequence=>50
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_CLOSE_WINDOW'
,p_process_name=>'Close Dialog'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when=>'CREATE,SAVE,DELETE'
,p_process_when_type=>'REQUEST_IN_CONDITION'
,p_internal_uid=>64824745001894440
);
wwv_flow_imp.component_end;
end;
/
